### ISSUE TITLE
Minifying the files throws error

### ISSUE THREAD

**Issue by benisonlg60** [olado/doT#247]
Message: ugly.parse is not a function

Stacktrace:
====================
TypeError: ugly.parse is not a function
    at Object.<anonymous> (C:\Users\BG049380\AppData\Roaming\npm\node_modules\dot-packer\index.js:38:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by epoberezkin** [comment]
I assume you try to minify doT.js, as index.js is only for node.js (and minified doT is already in the repo).
If so, the issue should be filed to uglifyjs.
Btw I had no issue minifying the bundle that included doT.
